version: 2
jobs:
  check:
    docker:
      - image: circleci/node:10.14.1
    steps:
      - checkout
      - run: yarn run install:dev
      - run: yarn run check
workflows:
  version: 2
  check:
    jobs:
      - check
